APP_ENV=development
APP_URL=http://localhost:3000
DATABASE_URL=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
AI_PROVIDER=
AI_API_KEY=
# Stripe test-mode (do not commit real values)
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=
